### ISSUE TITLE
`http: multiple response.WriteHeader calls` messages when used with `negroni`

### ISSUE THREAD

**Issue by jeromenerf** [donovanhide/eventsource#19]
I just replaced `antage/eventsource` with `donovanhide/eventsource` in my application to benefit from the replay feature. :ok_hand: 

As of now, everything works just fine: events are pushed on demand and replayed as needed, however I noticed some intriguing `2016/01/26 16:08:09 http: multiple response.WriteHeader calls` messages in the logs.

I am using the `Handler("channel")` method through a codegangsta/negroni middleware and I created a minimal app to reproduce the problem.

This could be related to https://github.com/codegangsta/negroni/commit/1398c5e220e5d6d1c4043f0eb9720f11e079e5ce but I am not quite sure how I could fix / workaround this issue.

Have you tried to use `eventsource` in some kind of middleware system?

## Steps to reproduce

```go
package main

import (
	"fmt"
	"net/http"
	"time"

	"github.com/codegangsta/negroni"
	"github.com/donovanhide/eventsource"
)

type TimeEvent time.Time

func (t TimeEvent) Id() string    { return fmt.Sprint(time.Time(t).UnixNano()) }
func (t TimeEvent) Event() string { return "Tick" }
func (t TimeEvent) Data() string  { return time.Time(t).String() }

const (
	TICK_COUNT = 1000
)

func TimePublisher(srv *eventsource.Server) {
	start := time.Date(2013, time.January, 1, 0, 0, 0, 0, time.UTC)
	ticker := time.NewTicker(time.Second)
	for i := 0; i < TICK_COUNT; i++ {
		<-ticker.C
		srv.Publish([]string{"time"}, TimeEvent(start))
		start = start.Add(time.Second)
	}
}

func main() {
	router := http.NewServeMux()
	SSE := eventsource.NewServer()
	defer SSE.Close()
	go TimePublisher(SSE)
	router.HandleFunc("/stream", SSE.Handler("time"))

	n := negroni.Classic()
	n.UseHandler(router)
	n.Run("127.0.0.1:3456")
}
```

Connect with:

```sh
curl 'http://127.0.0.1:3456/stream'
```

Observe logs: 
```
go run test.go
[negroni] listening on 127.0.0.1:3456
[negroni] Started GET /stream
2016/01/26 16:16:46 http: multiple response.WriteHeader calls
```

**Comment by donovanhide** [comment]
Hi, first of all thanks for trying out the code and the bug report :-)

To answer your last question first, I haven't used this package with any other middleware systems. It looks like the Flush() here is causing your problem:

https://github.com/donovanhide/eventsource/blob/master/server.go#L78

which invokes:

https://github.com/golang/go/blob/2c12b81739ec2cb85073e125748fcbf5d2febb2c/src/net/http/server.go#L279

which writes the header :-) This is needed for eventsource streams which don't start broadcasting immediately (unlike your example code) so that the client can inspect the headers first and know that the response is in fact an event stream and the carry on waiting for some events to come later. 

So, to solve your actual problem, you could avoid `n.Run(...)` and set up your own `http.ListenAndServe()` which has a router that sends some request paths to your `SSE` server and others to a Negroni set of handlers. I guess the question is whether you actually need some middleware functionality for your eventsource handler? If so, I guess this test needs beefing up as there may be some issue within negroni itself when handling flushes:

https://github.com/codegangsta/negroni/blob/c7477ad8e330bef55bf1ebe300cf8aa67c492d1b/response_writer_test.go#L144-L150

Let me know if you need more help!

**Comment by donovanhide** [comment]
This looks like the easiest way to solve what your doing:
https://github.com/codegangsta/negroni#route-specific-middleware

**Comment by jeromenerf** [comment]
Thanks @donovanhide !

I took some time to try and reproduce the bug but went short on going further.

Anyway, yes, the eventsource stream could benefit from the existing middlewares such as permissions, logger and so on.

I'll keep you in touch ;)

**Comment by donovanhide** [comment]
Actually, there was a simple fix :-) See if it works for you now!
